[tool.poetry]
name = "pytorchddp"
version = "0.1.0"
description = ""
authors = ["heeler <jamie.sherman@alleninstitute.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
